packages: []

catalogs:
  build:
    '@nuxt/devtools': ^2.3.2
    '@nuxt/eslint': ^1.3.0
    '@nuxt/icon': 1.12.0
    '@nuxt/test-utils': ^3.17.2
    '@nuxtjs/color-mode': ^3.5.2
    '@nuxtjs/i18n': 9.5.4
    '@pinia/nuxt': ^0.10.1
    '@unocss/eslint-config': ^66.1.0-beta.10
    '@unocss/nuxt': ^66.1.0-beta.10
    '@vite-pwa/nuxt': ^1.0.0
    '@vueuse/nuxt': ^13.1.0
    nuxi: ^3.25.0
    nuxt: ^3.16.2
    unocss: ^66.1.0-beta.10
    unplugin: ^2.2.2
    vite: ^6.2.5

  conflicts_frontend_catalog_frontend:
    shadcn-nuxt: catalog.frontend

  dev:
    '@antfu/eslint-config': ^4.11.0
    '@vue/test-utils': ^2.4.6
    eslint: ^9.24.0
    eslint-plugin-format: ^1.0.1
    happy-dom: ^17.4.6
    husky: ^9.1.7
    lint-staged: ^15.5.1
    playwright-core: ^1.52.0
    typescript: ^5.8.3
    vitest: ^3.1.2
    vue-tsc: ^2.2.8
  frontend:
    '@vueuse/core': ^13.1.0
    class-variance-authority: ^0.7.1
    clsx: ^2.1.1
    lucide-vue-next: ^0.503.0
    pinia: ^3.0.1
    reka-ui: ^2.2.0
    shadcn-nuxt: 2.1.0
    tailwind-merge: ^3.2.0
    tailwindcss: ^4.1.5
    tw-animate-css: ^1.2.8
    vue: ^3.5.13
    zod: ^3.24.3

  icons:
    '@iconify-json/carbon': ^1.2.8
    '@iconify-json/twemoji': ^1.2.2

  server:
    install: ^0.13.0

    node-telegram-bot-api: ^0.66.0
  tailwind:
    '@tailwindcss/vite': ^4.1.5
onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
